services:
  traedir:
    image: nginx:alpine
    container_name: traediro
    volumes:
      - ./traedir.conf:/etc/nginx/conf.d/default.conf
      - ./traedir.html:/usr/share/nginx/html/403.html
    labels:
      - traefik.enable=true
      - traefik.http.routers.traedir-catchall.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.traedir-catchall.entrypoints=web
      - traefik.http.routers.traedir-catchall.priority=1
      - traefik.http.services.traedir-catchall.loadbalancer.server.port=80
